name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx build -t online-cinema \
        --build-arg NODE_ENV=production \
        --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
        --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
        --build-arg TELEGRAM=${{ secrets.TELEGRAM }} .

    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: ./Dockerfile
        target: ~/online-cinema

    - name: Deploy to VPS
      run: |
        ssh -i ${{ secrets.VPS_SSH_KEY }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'docker-compose down && docker-compose up -d'