name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env: 
          NODE_ENV:  ${{ secrets.NODE_ENV }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TELEGRAM:  ${{ secrets.TELELGRAM }}
          JWT_SECRET:  ${{ secrets.JWT_SECRET }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NODE_ENV, MONGO_URI, TELEGRAM
          script: |
            cd ~
            pm2 stop online-cinema
            rm -rf online-cinema
            git clone ${{ secrets.REPOSITORY }}
            ~/deploy.sh
            cd online-cinema
            yarn install
            yarn build
            pm2 start dist/main.js --name online-cinema